### ISSUE TITLE
0.3.x alpha: vault plugin requests tokens too often

### ISSUE THREAD

**Issue by seamusabshere** [faradayio/cage#100]
I'm used to hooks only running on `cage pull`. And that's where I got my secrets, using a script in `config/hooks/pull.d`.

I switched to using the vault plugin. Now it appears to re-request vault tokens every time I run `cage source unmount`, etc.

**Comment by emk** [comment]
Ah, yup. The `vault` was exclusively used for `export` before and it doesn't cache tokens locally. Thank you for catching this!
