### ISSUE TITLE
easy way to say "ignore this src" (without deleting, run the image instead)

### ISSUE THREAD

**Issue by seamusabshere** [faradayio/cage#18]
currently, as far as i know, the only way to put a service into image mode is to `rm`/`mv` it from the `src` dir.

it would be nice to just `touch src/mything1/CAGE-IGNORE` to make cage pretend it's not in `src/`

**Comment by seamusabshere** [comment]
(don't make it a dotfile because then you will pull your hair out trying to figure out why cage isn't running it from `src/` :))

**Comment by emk** [comment]
Thank you for the suggestion! This sort of feedback is really valuable.

This is definitely on the TODO list; I'm just trying to think of a way to do it that isn't hugely confusing.

**Comment by seamusabshere** [comment]
for what it's worth, we used to have a `checkin` / `checkout` commands... when you wanted to know what was in image vs src mode, you just said `status`

**Comment by emk** [comment]
We do already have the equivalent of `status`. Try `cage repo list` for an overview. If I implemented this using a CLI interface, you'd be able to see the full status there. Hopefully including git stuff some day (see #13).

The original cage's `checkin` and `checkout` commands were mostly replaced with the `mode` command, IIRC. Except implementing this would be much easier using the dotfile (`.conductor/local.yml`, for example) you say that you don't want. :-)

Is it reasonable to ask people to run `cage repo list` if they're trying to figure out why a repo isn't getting mounted? That seems more obvious to me than having magic files tucked away in various directories.

**Comment by seamusabshere** [comment]
sure

while you're at it, why not just make it `cage repo` (implied "list")

**Comment by emk** [comment]
> why not just make it cage repo (implied "list")

`cage repo` triggers the help screen for all the repo-related commands, of which there will be several more. It's slightly tricky to have both `cage repo` and `cage repo clone` both be valid commands, though not impossible. I might rename it to `cage repo status`, though.

**Comment by emk** [comment]
There might be a more succinct and global `cage status` at some point as well.

**Comment by seamusabshere** [comment]
this is pretty urgent, because i don't like deleting or moving src repos, but at this point i have almost everything in my src dir... probably not healthy to run the app with a bunch of code that is more likely than images to go out of date

**Comment by seamusabshere** [comment]
(in other words, src dirs are more likely to bitrot than image dirs, but i don't want to constantly `rm` or mv` them...)

@emk ack my impression that this is urgent vs. https://github.com/faradayio/cage/milestone/1 ?

**Comment by emk** [comment]
@seamusabshere It turns out that the lack of this makes #24 (already on the short list) _really_ awkward in practice. Bumping onto the short list for the initial announcement.
