### ISSUE TITLE
Don't let docker create the src directory

### ISSUE THREAD

**Issue by dkastner** [faradayio/cage#23]
If you have a library defined that gets mapped to a volume, any container that runs that uses that volume will create `./src/library`, which means `src` is now owned by root. This breaks `cage repo clone`.

**Comment by emk** [comment]
This is almost certainly a a different bug: We shouldn't be generating library mounts for containers unless the library directory already exists locally.

**Comment by emk** [comment]
I think I have a fix for this in 250203f. I was missing a check for mounting library repos.

Could you please verify this either against `master` or against 0.0.23 when it comes out?
