### ISSUE TITLE
Provide a working Node+yarn example with in-tree Dockerfiles and source

### ISSUE THREAD

**Issue by emk** [faradayio/cage#24]
Not everybody will have have one git repository per Docker image. For smaller projects, you may just want to keep the `Dockerfile` and supporting source code directly under `src` without using an external repo.

To make this work, we need to:

- [x] Add a new subdirectory of `examples` containing a tiny Node.js project.
- [x] Fix the `abs_path` plugin to handle relative paths in `build:`.
- [x] Allow mounting local source directories into containers.
- [x] Rename `Repo` → `Repos` and `cage repo` → `cage source`.
- [x] Allow _not_ mounting local source directories into containers (aka #18).
- [x] Moved to #27. ~~Figure out what to do about our default `.gitignore` and the `src` directory.~~
- [x] Redesign `libraries.yml` for our release while we're at it. Maybe as `config/sources.yml`?

**Comment by emk** [comment]
@dkastner @seamusabshere `cage repo` is about to become obsolete as a command name, because we will very shortly support both external source directories and also local source in the main repo.

How do you feel about `cage source list`, `cage source clone myservice`, `cage source unmount myservice` (equivalent to the old `mode image`) and `cage source mount myservice` (equivalent to `mode repo`)?

**Comment by seamusabshere** [comment]
i _love_ it

**Comment by seamusabshere** [comment]
"source" and "mount" are _exactly_ the right words

**Comment by dkastner** [comment]
`source` sounds good to me too
