### ISSUE TITLE
Auto-`up` after `mount` and `unmount`?

### ISSUE THREAD

**Issue by emk** [faradayio/cage#36]
After running the `mount` and `unmount` commands, automatically re-run `up`.

Potential drawbacks: We might start services that weren't running before.

**Comment by dkastner** [comment]
I'm not sure this is a good idea. I used to have all kinds of helpers like this in the old cage but they ended up being a nuisance 80% of the time.

**Comment by emk** [comment]
Yeah, that's an excellent point. If we do this at all, it probably ought to wait until after we have the ability to poll Docker and see which pods/containers are currently up, and which would need to be restarted. Moving off of milestone and into RFC status for further discussion.

**Comment by emk** [comment]
There doesn't currently seem to be any consensus that this is a good idea.

I suppose that we could be a bit more precise, now that we have detailed container state: We could selectively re-`up` only those services that are (1) affected by the volume mount change and (2) already running in the user's environment.

But I'm not convinced this is actually a good idea, especially now that we warn the user to re-run `up` after they run `mount`.

**Comment by emk** [comment]
Yeah, after consideration, I'm closing this RFC for now. Thank you for your feedback!
