### ISSUE TITLE
why db.yml vs. db.metadata.yml?

### ISSUE THREAD

**Issue by seamusabshere** [faradayio/cage#42]
Is it just anything that is not docker-compose v2 standard must go in metadata?

**Comment by emk** [comment]
Yes. See https://github.com/faradayio/cage/issues/28 for an explanation with links to upstream bugs, etc.

We're really determined to use standard `docker-compose.yml` files, which specifically forbid non-standard, pod-level metadata, and there are unit tests to make sure that `docker-compose` will refuse to run if any such metadata is present.

**Comment by seamusabshere** [comment]
is this explained in the docs?

**Comment by seamusabshere** [comment]
attempting to fix in https://github.com/faradayio/cage/pull/46
