### ISSUE TITLE
`cage stop` only stops development target

### ISSUE THREAD

**Issue by seamusabshere** [faradayio/cage#50]
unclear how to tell it to stop test placeholders, for example

**Comment by emk** [comment]
--target=test

Le 27 oct. 2016 5:03 PM, "Seamus Abshere" <notifications@github.com> a
écrit :

**Comment by seamusabshere** [comment]
```
$ cage stop --target=test
error: Found argument '--target' which wasn't expected, or isn't valid in this context

USAGE:
    cage stop [<POD_OR_SERVICE>]

For more information try --help
```

**Comment by emk** [comment]
Before the `stop`. See `--help`.

Le 27 oct. 2016 5:16 PM, "Seamus Abshere" <notifications@github.com> a
écrit :
