### ISSUE TITLE
`cage test` caveats and possible affordances

### ISSUE THREAD

**Issue by seamusabshere** [faradayio/cage#51]
i think we should bake more intelligence into `cage test`

**Easy way to get a false negative**: forgetting to run `cage --target test up`

**Proposed solution**: detect somehow if the test target isn't "up" (yes, this makes assumptions about target naming)

**Easy way to get a false positive**: forgetting to `cage source mount` after you change a test

**Proposed solution**: warn if testing against an unmounted service

**Comment by emk** [comment]
These both sound like excellent ideas!

> detect somehow if the test target isn't "up"

The best way to do this is to look for pods which are enabled in test mode (according to `cage status`) but which contain services that are not RUNNING. This is actually pretty simple and well-defined.

> warn if testing against an unmounted service

Yeah, this seems reasonable enough.

**Comment by emk** [comment]
Part of this is already mentioned under #6.
