### ISSUE TITLE
`cage source unmount all`

### ISSUE THREAD

**Issue by seamusabshere** [faradayio/cage#53]

**Comment by dkastner** [comment]
Actually, what I've been wanting is:

`cage unmount foo` as a shortcut to `cage source unmount foo`
`cage mount foo` as a shortcut to `cage source mount foo`
`cage unmount` as a shortcut to `cage source unmount <everything>`
`cage mount` as a shortcut to `cage source mount <everything>`

**Comment by seamusabshere** [comment]
( i think `cage mount` as a command in itself would be confusing, people would run that to get help )

**Comment by devTristan** [comment]
`cage mount --all`
