### ISSUE TITLE
cage restart

### ISSUE THREAD

**Issue by devTristan** [faradayio/cage#54]
From the help:

```
cage up     # Restart application
```

This only restarts containers that are down, or whose configuration has changed. I propose a new command:

```
cage restart
cage restart my_app
```

`cage restart` would restart all containers, and `cage restart x` would restart a given container

**Comment by emk** [comment]
This is an easy feature. Let's do it.

**Comment by emk** [comment]
This will be in the next cage release! Thank you for the feature suggestion. :-)
