### ISSUE TITLE
0.3.x alpha: auto-mounts everything

### ISSUE THREAD

**Issue by seamusabshere** [faradayio/cage#99]
1. i had 1 of 10 pods mounted
2. i upgraded to 0.3.x and did `cage pull`
3. all of my pods were mounted

**Comment by emk** [comment]
Could you please reproduce this with `RUST_LOG=cage=trace` enabled, and send me the logs via a private channel?

**Comment by seamusabshere** [comment]
false alarm: i had `rm -rf .cage` in order to prove out vault plugin
